### ISSUE TITLE
AttributeError: 'QModule' object has no attribute 'stride'

### ISSUE THREAD

**Issue by PEAKWEI** [ucbrise/actnn#33]
AttributeError: 'QModule' object has no attribute 'stride'

**Comment by PEAKWEI** [comment]
Traceback (most recent call last):
  File "train.py", line 624, in <module>
    main(opt)
  File "train.py", line 521, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 198, in train
    gs = max(int(model.stride.max()), 32)  # grid size (max stride)
  File "/usr/local/python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'QModule' object has no attribute 'stride'
